### ISSUE TITLE
CIAlign installed by pip3 returned an error that 'no module name  _version'

### ISSUE THREAD

**Issue by ugobananas** [KatyBrown/CIAlign#15]
Hi,

I use 'pip3 install cialign' for installation. When I used it, it gave an error that 'no module name _version'. I checked that _version.py existed. Somehow it cannot be used. Could you please fix this? Thanks!

**Comment by KatyBrown** [comment]
Hi,

Thanks for the feedback.  We've not been able to reproduce this error - please can you give us some more information?

It would be helpful to see the full error message and the output of the commands `pip3 list`, `which python`  and `python --version` on your terminal.  A screenshot of all of these is fine.

Also, please note that your last issue #13 was addressed since our latest pip release, so to access this functionality you would need to clone the repo using `git clone` rather than installing via pip.

Thanks very much,
Katy

**Comment by ugobananas** [comment]
Hi,

`git clone` can solve this problem. Thanks! 

Attached is the screenshot of the error report. I used Red Hat Linux system. Hope it help!
![屏幕快照 2020-10-05 下午10 47 41](https://user-images.githubusercontent.com/65168005/95098895-d57ea100-0761-11eb-837e-c8737d25fcf8.png)

**Comment by KatyBrown** [comment]
Hi @ugobananas,

Thanks for spotting this and letting us know! There was a problem with the path in the pip version of the code which we missed by using the git version.

It should be OK now in the latest release on pip - [v1.0.9](https://pypi.org/project/cialign/) - and the[ latest Github release](https://github.com/KatyBrown/CIAlign/releases/tag/v1.0.9).

Please let us know if you have any more problems.
Thanks very much,
Katy
