### ISSUE TITLE
Cleaning up very large insertions

### ISSUE THREAD

**Issue by dnieuw** [KatyBrown/CIAlign#17]
Hi, I have tried out CIAlign on an alignment, which has some very bad issues, such as very long insertions, due to the presence of long stretches of X's. I have seen that it is possible to increase the insertion_max_size, which I did (to 9999, so basically infinite). Doing that, however, increased the time that CIAlign ran dramatically (I had to kill it).

I ran:
`CIAlign --infile test_cluster.aln --outfile test_cluster_clean.aln --remove_divergent --remove_insertions --insertion_max_size 9999`

Is that normal, am I doing something stupid, or can this be fixed?

I have attached the alignment file:
[test_cluster.zip](https://github.com/KatyBrown/CIAlign/files/5384396/test_cluster.zip)

**Comment by KatyBrown** [comment]
Hi,

I'm afraid at the moment this will increase the running time a lot, as we run through every insertion size from insertion_min_size to insertion_max_size at every position. We may be able to optimise this better in a later release, but for now I'd suggest using the approximate length of your longest insertion, rather than using a very large number.

Thanks very much!

**Comment by lukaszsobala** [comment]
I would also be interested in this function!
