### ISSUE TITLE
The sequences in your alignment are not all the same length

### ISSUE THREAD

**Issue by majie5976** [KatyBrown/CIAlign#20]
Hi @KatyBrown ,
Thanks for offering wonderful MSA tool. 
I was trying to have consensus sequences from slightly different length assembled contigs of a specific repeat element, but unfortunately encountered with an error,  I don't have experience to deal with python script. Command and along with error below, 
 **"/CIAlign-1.0.9/CIAlign$ python3 CIAlign.py --infile CalipSat.fasta --outfile_stem STEM
Unable to init server: Could not connect: Connection refused
Unable to init server: Connection refused

(CIAlign.py:28207): Gdk-CRITICAL **: 22:19:13.626: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
/home/mj/CIAlign-1.0.9/CIAlign/utilityFunctions.py:89: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  arr = np.array(seqs[1:])
Error: The sequences in your alignment are not all the same length."**
Could you please suggest me any solution of it!
Thanks

**Comment by KatyBrown** [comment]
Hi @majie5976,
Thanks very much - I'm glad you like our tool.

I think the problem here is that CIAlign is designed to using on aligned FASTA files - https://en.wikipedia.org/wiki/Multiple_sequence_alignment - which are padded with gaps (-) to make them all the same length.

If you are working with multiple newly assembled contigs, you would need to align them with each other using a tool such as MUSCLE, Clustal or MAFFT prior to using CIAlign to make the appropriate input.

If you are looking at the alignments used to assemble the contigs, you would need to use gaps to align the input.
e.g.
```
>seq1
ATGGCGGT--------

>seq2
----CGGTACGTG---

>seq3
---------CGTGACT
```

I hope this helps, please let us know if you have any other questions.
Katy

**Comment by majie5976** [comment]
Hi @KatyBrown,
Thank you for the response, I got it. Your explanation worked in my case and back on the right track now !
Thanks again !
majie
